on:
  workflow_dispatch:
    inputs:
      iterations:
        description: Number of iterations
        type: number
        default: 250000


jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        py_version: 
          - "3.10"
          - "3.11"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup python ${{ matrix.py_version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.py_version }}
      - name: Setup pythonfuzz
        run: pip install -r requirements-dev.txt
      - name: Run fuzzer (${{ inputs.iterations }} iterations)
        run: |
          python fuzz.py -n ${{ inputs.iterations }}
