on:
  workflow_dispatch:
    inputs:
      iterations:
        description: Number of iterations
        type: number
        default: 250000
      do_shard:
        description: Run it on 4 separate machines (`n` on each)?
        type: boolean
        default: false


jobs:
  fuzzer:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        py_version: 
          - "3.10"
          - "3.11"
          - "3.12"
        do_shard:
          - ${{ inputs.do_shard }}
        shard_index: [0, 1, 2, 3]
        exclude:
          - do_shard: false
        include:
          - do_shard: false
            py_version: "3.10"
          - do_shard: false
            py_version: "3.11"
          - do_shard: false
            py_version: "3.12"
    name: ${{ inputs.do_shard && format('Run fuzzer (Python {0}, shard {1})', matrix.py_version, inputs.shard_index) || format('Run fuzzer (Python {0})', matrix.version) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup python ${{ matrix.py_version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.py_version }}
      - name: Setup pythonfuzz
        run: pip install -r requirements-dev.txt
      - name: Run fuzzer (${{ inputs.iterations }} iterations)
        run: |
          python fuzz.py -n ${{ inputs.iterations }}
