on:
  workflow_dispatch:
    inputs:
      iterations:
        description: Number of iterations
        type: number
        default: 250000


jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        py_version: 
          - "3.10"
          - "3.11"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup python ${{ matrix.py_version }}
        uses: actions/setup-python@v4.6.1
        with:
          python-version: ${{ matrix.py_version }}
      - name: Setup pythonfuzz >=1.0.11
        run: pip install -r requirements-dev.txt
      - name: Run tests
        run: |
          python fuzz.py -n ${{ inputs.iterations }}
