on:
  push:
    branches: [ main, "**workflow**" ]
  pull_request:
    branches: [ main, "**workflow**" ]

  workflow_dispatch:


jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        py_version: 
          - "3.10"
          - "3.11"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup python ${{ matrix.py_version }}
        uses: actions/setup-python@v4.6.1
        with:
          python-version: ${{ matrix.py_version }}
      - name: Run tests
        run: |
          chmod +x ./run_tests.sh
          ./run_tests.sh --verbose
